version: '3.1'
# fuck docker, this shit hardly works because the wordpress volume mount is vbox share as root and can't be accessed from the running container.
# so just zip up the paintthescene directory and update that way....yea i know, it's bullshit.
services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - ./paintthescene:/var/www/html/wp-content/themes/paintthescene
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
